language: node_js

os: linux

node_js:
  - lts/*

jobs:
  include:
    - stage: test
      script:
        - yarn build 
        - yarn lint
        - yarn test
    # Define the release stage that runs semantic-release
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        cleanup: false
        skip_cleanup: true
        script:
        - yarn build
        - npx semantic-release